Repository AnkitMajee/DataStructureInCpp, pull requests merged in 2024-10, with the labels that each got.

#15 Created QuickSort.cpp and radixSort.cpp
  7 Sorting/QuickSort.cpp
  7 Sorting/RadixSort.cpp
Labels: Hacktoberfest-Accepted

#18 #10 - Added 2 Array Questions (20, 21) in Arrays directory.
  6 Array/20. Product of Array elements except itself.cpp
  6 Array/21. Second Largest Element in an Array.cpp
Labels: Hacktoberfest-Accepted

#19 #14 - Added 2 Questions based on Sorting (Merge Sort & Sort 0's and 1's in an Array)
  7 Sorting/MergeSort.cpp
  7 Sorting/Sort 0's and 1's in an Array.cpp
Labels: Hacktoberfest-Accepted

#20 Add stack folder and Stack Implementation code
  15 Stack/stackImplementation.cpp
  16 Binary Search/BinarySearch.cpp
  16 Binary Search/minimum-in-rotated-sorted-array.cpp
  16 Binary Search/peak-element-in-array.cpp
  16 Binary Search/search-element-in-a-rotated-sorted-array.cpp
Labels: enhancement, Hacktoberfest-Accepted

#21 Added new binary search solution
  16 Binary Search/smallest_missing_element.cpp
  16 Binary Search/smallest_missing_element.exe
Labels: Hacktoberfest-Accepted

#22 Added Modular Exponentiation
  14 Maths/23. Modular Exponentiation.cpp
Labels: Hacktoberfest-Accepted

#23 Added program 20 in Recurssion
  13 Recursion/20.SortAStackUsingRecurssion
  13 Recursion/20.SortAStackUsingRecurssion.cpp
Labels: Hacktoberfest-Accepted

#24 Added topological sort
  7 Sorting/TopologicalSort.cpp
Labels: Hacktoberfest-Accepted

#26 added deque file
  T) Deque/239.Sliding Window Maximum.cpp
  T) Deque/641. Design Circular Deque.cpp
  T) Deque/Readme.md
Labels: Hacktoberfest-Accepted

#27 Solved a problem(Aggresive Cows) using Binary Search
  16 Binary Search/Aggresive_cows.cpp
Labels: Hacktoberfest-Accepted

#29 Question Based on Binary Search
  Binary Search.cpp
Labels: Hacktoberfest-Accepted, New Question

#31 tree interview question added
  S) Tree/5. Binary Tree Maximum Path Sum.cpp
Labels: enhancement, Hacktoberfest-Accepted, New, New Question

#32 Added a cpp code to make comparisons among various different sorting …
  G) Searching & Sorting/Comaprison.cpp
  G) Searching & Sorting/Reults.py
Labels: enhancement, Hacktoberfest-Accepted, New, Code, New Question

#33 Created SerializeAndDeserializeBinaryTree.cpp
  S) Tree/SerializeAndDeserializeBinaryTree.cpp
Labels: Hacktoberfest-Accepted, New Question

#34 Comparison and Visualisation of Sorting Algorithms
  G) Searching & Sorting/Comparisons & Visualization/Comaprison.cpp
  G) Searching & Sorting/Comparisons & Visualization/Reults.py
Labels: enhancement, Hacktoberfest-Accepted

#35 Created ReverseNodesInKGroup.cpp
  Q) Linked List/ReverseNodesInKGroup.cpp
Labels: Hacktoberfest-Accepted, New Question

#36 Created MergeKSortedLists.cpp
  Q) Linked List/MergeKSortedLists.cpp
Labels: Hacktoberfest-Accepted, New Question

#38 Added solution of "Reverse a Stack Using Recursion"
  O) Stack/reverseAstack.cpp
Labels: Hacktoberfest-Accepted, New Question

#40 Updated Contributor's Names
  README.md
Labels: enhancement, Hacktoberfest-Accepted, New

#43 Adding my work
  .vscode/settings.json
  .vscode/tasks.json
  Intervals/merge-intervals.cpp
  Intervals/summary-ranges.cpp
  O) Stack/minimum-add-valid.cpp
  O) Stack/valid_paranthesis.cpp
  P) Binary Search/koko-eating-bananas.cpp
  P) Binary Search/search-in-2D-matrix.cpp
Labels: Hacktoberfest-Accepted, Code, New Question

#42 Added Well Commented Level Order Traversal Algorithm to the trees section
  S) Tree/6.levelOrderTraversal.cpp
Labels: Hacktoberfest-Accepted, New, New Question

#30 Linear Search
  Linear Search
Labels: Hacktoberfest-Accepted

#44 Added 3 Question to stack and 1 Question to Tree.
  O) Stack/BasicCalculator.cpp
  O) Stack/ImplementStackUsingQueue.cpp
  O) Stack/NextGreaterEelementInArrayUsingStack.cpp
  S) Tree/HeightOfABinaryTree.cpp
Labels: Hacktoberfest-Accepted, New

#46 I have added Binary Search Tree Code
  .DS_Store
  S) Tree/Binary Search Tree.cpp
Labels: Hacktoberfest-Accepted, New Question

#48 Create mergesort.c++
  mergesort.c++
Labels: Hacktoberfest-Accepted

#50 I have added Circular Linked List
  .DS_Store
  Q) Linked List/CircularLinkedList.cpp
Labels: Hacktoberfest-Accepted, New Question

#52 I have added Trie Implementation in New Folder
  .DS_Store
  U) Trie/.DS_Store
  U) Trie/Trie Implementation.cpp
Labels: Hacktoberfest-Accepted, New, New Algo, New Question

#54 I have Added the zig-zag traversal code
  S) Tree/Zig-ZagTraversal.cpp
Labels: Hacktoberfest-Accepted, New Question

#55 Find Square Root Of n using Binary Search
  P) Binary Search/SquareRootOfNumberUsingBinarySearch.cpp
Labels: Hacktoberfest-Accepted, New Algo

#59 Added solution of <vertical traversal of binary tree># 58
  S) Tree/verticalTraversal.cpp
Labels: Hacktoberfest-Accepted, New, New Question

#61 Add function to find the longest subarray with zero sum
  F) Array/Subarray/8.2.6Longest Subarray Zero Sum.cpp
Labels: Hacktoberfest-Accepted, New Question

#64 Added few important interview questions
  D) pattern/4.13 Anagram.cpp
  G) Searching & Sorting/BinarySearch.cpp
Labels: Hacktoberfest-Accepted, New

#65 added program to pascals triangle
  D) pattern/pascals triangle.cpp
Labels: Hacktoberfest-Accepted, New Question

#69 Add Maximum Consecutive Ones
  F) Array/23. Maximum Consecutive Ones.cpp
Labels: Hacktoberfest-Accepted, New Question

#68 Add function to count distinct elements in every window of size k
  F) Array/22.Count Distinct Element in Every K Size Window.cpp
Labels: Hacktoberfest-Accepted

#79 Added a dsa question and its solution inside tree folder
  F) Array/Combination Sum II/README.md
  F) Array/Combination Sum II/combination-sum-ii.cpp
  S) Tree/Vertical sum/README.md
  S) Tree/Vertical sum/vertical-sum.cpp
Labels: Hacktoberfest-Accepted, New Question

#74 Implemented the Set Matrix Zero Problem
  F) Array/2D array/6.Set_Matrix_Zero.cpp
Labels: Hacktoberfest-Accepted, New, New Question

#71 Create 24. Maximum Swap
  N) Maths/24. Maximum Swap
Labels: Hacktoberfest-Accepted

#80 Added dsa question + solution inside array
  F) Array/Union of Two Sorted Arrays/README.md
  F) Array/Union of Two Sorted Arrays/union-of-two-sorted-arrays.cpp
Labels: Hacktoberfest-Accepted

#70 Create 1480. Running Sum of 1d Array.cpp
  F) Array/1480. Running Sum of 1d Array.cpp
Labels: Hacktoberfest-Accepted, New, New Question

#81 added files inside tree
  S) Tree/Level of Nodes/Level of Nodes.docx
  S) Tree/Level of Nodes/source_code.cpp
Labels: Hacktoberfest-Accepted

#82 added files inside bit magic
  J) Bit Magic/Number of 1 Bits/Number of 1 Bits.docx
  J) Bit Magic/Number of 1 Bits/source code.cpp
Labels: Hacktoberfest-Accepted

#83 Solved the Group Anagrams Problem
  I) String/14.Group_Anagrams.cpp
Labels: Hacktoberfest-Accepted

#85 Solved Valid Palindrome Problem
  I) String/15.Valid_Palindrome.cpp
Labels: Hacktoberfest-Accepted

#86 Added Solution of "Best time to Buy and sell stock II Problem #76
  Best-time-to-buy-stock.cpp
Labels: Hacktoberfest-Accepted

#87 #62 Done Find Largest Rectangle in Histogram in C++
  O) Stack/largestareainhistogram.cpp
Labels: Hacktoberfest-Accepted

#88 Fixes #77: Implement N Queens Problem Using Backtracking
  M) Recursion/N-Queen.cpp
Labels: Hacktoberfest-Accepted, New Question

#93 Search 2D Matrix
  F) Array/2D array/Search_2D_Matrix.cpp
Labels: Hacktoberfest-Accepted

#96 Added Graph and DP
  V) Dynamic Programming/Best-time-to-buy-stock.cpp
  V) Dynamic Programming/Longest Common Subsequesnce.cpp
  V) Dynamic Programming/Longest Common Subsequesnce.exe
Labels: Hacktoberfest-Accepted

#97 Dp question
  G) Searching & Sorting/g.js
  V) Dynamic Programming/Coin Change.cpp
  V) Dynamic Programming/Coin Change.exe
Labels: Hacktoberfest-Accepted

#98 Infix-To-Postfix
  O) Stack/infix_to_postfix.cpp
Labels: Hacktoberfest-Accepted

#99 Create Floor and Ceil in Sorted Array.
  P) Binary Search/Floor and Ceil in Sorted Array.
Labels: Hacktoberfest-Accepted

#101 Adding another 2 problems
  N) Maths/25. Sqaures_Of_A_Sorted_Array.cpp
  N) Maths/26. Ugly_Number_2.cpp
  P) Binary Search/Floor_and_Ceil_in_Sorted_Array.
Labels: Hacktoberfest-Accepted

#103 Fixes #102 : Implement Distinct Subsequences Question
  V) Dynamic Programming/Distinct Subsequences.cpp
Labels: Hacktoberfest-Accepted

#104 Added new codes in Binary Tree
  P) Binary Search/Floor_and_Ceil_in_Sorted_Array
  S) Tree/Vertical sum/README.md
  S) Tree/Vertical sum/vertical-sum.cpp
  S) Tree/successor_predecessor.cpp
Labels: Hacktoberfest-Accepted

#106 Create Sudoko_Solver.cpp
  M) Recursion/Sudoko_Solver.cpp
Labels: Hacktoberfest-Accepted

#107 Added code for Longest Increasing Subsequence
  V) Dynamic Programming/LongestIncreasingSubsequence.cpp
Labels: Hacktoberfest-Accepted

#108 Create CheckingBalancedBST
  S) Tree/CheckingBalancedBST
Labels: Hacktoberfest-Accepted

#110 Create Word_Search.cpp
  M) Recursion/Word_Search.cpp
Labels: Hacktoberfest-Accepted, New Question

#112 Create infix_to_prefix
  O) Stack/infix_to_prefix
Labels: Hacktoberfest-Accepted, New Question

#114 Evaluating_postfix_expression
  O) Stack/Evaluating_postfix_expression
Labels: Hacktoberfest-Accepted, New Question

#116 Evaluating_Prefix_expression
  O) Stack/Evaluating_Prefix_expression
Labels: Hacktoberfest-Accepted, New Question

#117 Added fibonacci in log(n)
  N) Maths/27.Fibonacci in logn.cpp
Labels: Hacktoberfest-Accepted

#118 Create lowestCommonAncestor.cpp
  S) Tree/lowestCommonAncestor.cpp
Labels: Hacktoberfest-Accepted

#119 Recursive QuickSort.cpp
  M) Recursion/QuickSort.cpp
Labels: Hacktoberfest-Accepted

#120 Added graph folder
  R) Intervals/merge-intervals.cpp
  R) Intervals/summary-ranges.cpp
  W) Graph/breadth_first_search.cpp
  W) Graph/depth_first_search.cpp
  W) Graph/dijkstras.cpp
  W) Graph/floyd_warshall.cpp
Labels: Hacktoberfest-Accepted, Code, New Question
